version: '3.9'

services:
  db:
    image: postgres:16.2
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=hygie
      - POSTGRES_PASSWORD=hygie
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
